name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout del código del repositorio
      - name: Checkout code
        uses: actions/checkout@v4

      # Despliegue vía SSH a EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/api2  # Cambia por tu ruta real en EC2
            git pull origin main
            source venv/bin/activate  # Si usas virtualenv
            pip install -r requirements.txt --quiet
            sudo systemctl restart api2  # Cambia por nombre de tu servicio systemd
